version: '3'
services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  api_service:
    build:
      context: ./api_service
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  transaction_service:
    build:
      context: ./transaction_service
    depends_on:
      - rabbitmq

  sql_service:
    build:
      context: ./sql_service
    ports:
      - "50051:50051"
    depends_on:
      - postgres