version: '3'
services:
  http-api:
    build:
      context: ./api_service
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # networks:
    #   - mynetwork

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      # RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit disk_free_limit 2147483648
    restart: always
    # volumes:
    #   - ./rabbitmq:/var/lib/rabbitmq
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # networks:
    #   - mynetwork

  transaction_service:
    build:
      context: ./transaction_service
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # networks:
    #   - mynetwork

                    
  sql-service:
    build:
      context: ./sql_service 
    ports:
      - "50051:50051"
    depends_on:
      - postgres  
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # networks:
    #   - mynetwork


  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      # PGDATA: "/var/lib/postgresql/data/pgdata"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # networks:
    #   - mynetwork



# networks:
#   mynetwork: {}

# networks:
#   mynetwork:
#     driver: bridge
#     driver_opts:
#         com.docker.network.enable_ipv6: "false"
#     ipam:
#       driver: default
#       config:
#         - subnet: 192.168.2.0/24
#           gateway: 192.168.2.1
